wandb_version: 1

batch_size:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.0001
seq_len:
  desc: null
  value: 350
d_model:
  desc: null
  value: 512
datasource:
  desc: null
  value: opus_books
lang_src:
  desc: null
  value: en
lang_tgt:
  desc: null
  value: it
model_folder:
  desc: null
  value: weights
model_basename:
  desc: null
  value: tmodel_
preload:
  desc: null
  value: null
tokenizer_file:
  desc: null
  value: tokenizer_{0}.json
experiment_name:
  desc: null
  value: runs/tmodel
_wandb:
  desc: null
  value:
    python_version: 3.9.22
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746337588.183641
    t:
      1:
      - 1
      - 40
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 40
      - 41
      - 49
      - 51
      - 55
      3:
      - 7
      - 16
      - 23
      4: 3.9.22
      5: 0.15.9
      8:
      - 5
    m:
    - 1: global_step
      6:
      - 3
